<a href="https://colab.research.google.com/github/ammumol/Bank-system-using-opps/blob/main/Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Numpy** and **Pandas**

######1. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix

In [2]:
import numpy as np
arr=np.arange(1,11)
print("The array containing numbers from 1 to 10: ",arr)
new_arr=arr.reshape(2,5)
print("\n2X5 matrix :")
new_arr

The array containing numbers from 1 to 10:  [ 1  2  3  4  5  6  7  8  9 10]

2X5 matrix :

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

2. Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

In [14]:
a=np.arange(1,21)
print("The array is ",a)
print("5th to 15th index elements are ",a[5:15])

The array is  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
5th to 15th index elements are  [ 6  7  8  9 10 11 12 13 14 15]

3. How to compute the mean, median, and standard deviation of a numpy array?Use the
array you created above

In [20]:
print("mean = ",np.mean(a))
print("median = ",np.median(a))
print("standard deviation = ",np.std(a))

mean =  10.5
median =  10.5
standard deviation =  5.766281297335398

4. Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of
shape (4,). Subtract y from each row of x using broadcasting.

In [4]:
x=np.array([[1,3,4,6],[12,8,6,10],[6,20,9,7]])
y=np.array([4,7,25,12])
print("3X4 array: \n",x)
print("1D array",y)
result=x-y
print("X-Y=\n",result)

3X4 array:
 [[ 1  3  4  6]
 [12  8  6 10]
 [ 6 20  9  7]]
1D array [ 4  7 25 12]
X-Y=
 [[ -3  -4 -21  -6]
 [  8   1 -19  -2]
 [  2  13 -16  -5]]

5. Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data. (Score: 2)

In [11]:
import pandas as pd
data={"name":["Ancy","John","Ram","Tom","Ann","Max","Liya","Jose","Maya","Rahna"],"age":[30,28,23,25,27,35,29,40,43,39],"gender":["F","M","M","M","F","M","F","M","F","F"]}
df=pd.DataFrame(data)
df

    name  age gender
0   Ancy   30      F
1   John   28      M
2    Ram   23      M
3    Tom   25      M
4    Ann   27      F
5    Max   35      M
6   Liya   29      F
7   Jose   40      M
8   Maya   43      F
9  Rahna   39      F

1) Add a new column to the data frame created in question 1, called occupation.
The values for this column should be Programmer, Manager, and Analyst,
corresponding to the rows in the dataframe.

In [12]:
df["occupation"]=["Programmer","Analyst","Manager","Analyst","Programmer","Manager","Analyst","Programmer","Manager","Analyst"]
df

    name  age gender  occupation
0   Ancy   30      F  Programmer
1   John   28      M     Analyst
2    Ram   23      M     Manager
3    Tom   25      M     Analyst
4    Ann   27      F  Programmer
5    Max   35      M     Manager
6   Liya   29      F     Analyst
7   Jose   40      M  Programmer
8   Maya   43      F     Manager
9  Rahna   39      F     Analyst

2) Select the rows of the dataframe where the age is greater than or equal to 30.

In [14]:
print(df[df["age"]>=30])

    name  age gender  occupation
0   Ancy   30      F  Programmer
5    Max   35      M     Manager
7   Jose   40      M  Programmer
8   Maya   43      F     Manager
9  Rahna   39      F     Analyst

3) Convert this dataframe to a CSV file and read that CSV file, and finally display
the contents.

In [18]:
df.to_csv("employees.csv",index=False)
new_df=pd.read_csv("employees.csv")
print(new_df)

    name  age gender  occupation
0   Ancy   30      F  Programmer
1   John   28      M     Analyst
2    Ram   23      M     Manager
3    Tom   25      M     Analyst
4    Ann   27      F  Programmer
5    Max   35      M     Manager
6   Liya   29      F     Analyst
7   Jose   40      M  Programmer
8   Maya   43      F     Manager
9  Rahna   39      F     Analyst